version: '3.8'

services:
  mysql-server:
    image: mysql:8.3
    container_name: mysql-server
    environment:
      MYSQL_DATABASE: "zabbix"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "zabbix"
      MYSQL_ROOT_PASSWORD: "zabbix"
    command: --character-set-server=utf8 --collation-server=utf8_bin
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - zabbix-net

  zabbix-server:
    image: zabbix/zabbix-server-mysql:latest
    container_name: zabbix-server
    environment:
      DB_SERVER_HOST: "mysql-server"
      MYSQL_DATABASE: "zabbix"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "zabbix"
      MYSQL_ROOT_PASSWORD: "zabbix"
    depends_on:
      - mysql-server
    ports:
      - "10051:10051"
    restart: unless-stopped
    networks:
      - zabbix-net
    healthcheck:
      test: ["CMD", "bash", "-c", "echo -e 'ZBXD\\x01\\x00\\x00\\x00\\x00\\x00\\x00\\x00' | nc -w 1 localhost 10051 || exit 1"]
      interval: 10s
      retries: 10

  zabbix-web:
    image: zabbix/zabbix-web-apache-mysql:latest
    container_name: zabbix-web
    environment:
      ZBX_SERVER_HOST: "zabbix-server"
      DB_SERVER_HOST: "mysql-server"
      MYSQL_DATABASE: "zabbix"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "zabbix"
      MYSQL_ROOT_PASSWORD: "zabbix"
      PHP_TZ: "America/Sao_Paulo"
    depends_on:
      - zabbix-server
    ports:
      - "80:8080"
    restart: unless-stopped
    networks:
      - zabbix-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      retries: 10

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/etc/prometheus
    ports:
      - "9090:9090"
    restart: unless-stopped
    networks:
      - zabbix-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      GF_INSTALL_PLUGINS: "alexanderzobnin-zabbix-app"
      GF_METRICS_ENABLED: "true"
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - zabbix-net

  node-app:
    build: ./src/node-app
    container_name: node-app
    ports:
      - "4000:3000"
    restart: unless-stopped
    networks:
      - zabbix-net

  collector-job:
    build:
      context: ./src/agents/collector
      dockerfile: Dockerfile
    container_name: collector-job
    volumes:
      - ./src/agents/collector:/app
      - ./data/processed:/data/processed
    depends_on:
      zabbix-web:
        condition: service_healthy
    environment:
      ZABBIX_URL: "http://zabbix-web:8080"
      ZABBIX_USER: "Admin"
      ZABBIX_PASS: "zabbix"
    networks:
      - zabbix-net
    command: ["python", "main.py"]

  analyzer-job:
    build:
      context: ./src   # <-- assim o build enxerga toda a pasta src/
      dockerfile: agents/analyzer/Dockerfile
    container_name: analyzer-job
    environment:
      INPUT_FILE: /data/processed/anomalies_dataset.csv
      OUTPUT_FILE: /data/processed/dataset_ready.csv
    volumes:
      - ./data:/data
      - ./src/infrastructure:/app/infrastructure
    depends_on:
      - collector-job
    networks:
      - zabbix-net

  prometheus-agent:
    image: zabbix/zabbix-agent2:latest
    container_name: prometheus-agent
    environment:
      ZBX_HOSTNAME: "Prometheus"
      ZBX_SERVER_HOST: "zabbix-server"
    depends_on:
      - zabbix-server
    restart: unless-stopped
    networks:
      - zabbix-net

  node-agent:
    image: zabbix/zabbix-agent2:latest
    container_name: node-agent
    environment:
      ZBX_HOSTNAME: "Node"
      ZBX_SERVER_HOST: "zabbix-server"
    depends_on:
      - zabbix-server
    restart: unless-stopped
    networks:
      - zabbix-net

  grafana-agent:
    image: zabbix/zabbix-agent2:latest
    container_name: grafana-agent
    environment:
      ZBX_HOSTNAME: "Grafana"
      ZBX_SERVER_HOST: "zabbix-server"
    depends_on:
      - zabbix-server
    restart: unless-stopped
    networks:
      - zabbix-net

  zabbix-agent2:
    image: zabbix/zabbix-agent2:latest
    container_name: zabbix-agent2
    environment:
      ZBX_HOSTNAME: "Zabbix server"
      ZBX_SERVER_HOST: "zabbix-server"
    depends_on:
      - zabbix-server
    restart: always
    networks:
      - zabbix-net

  mysql-agent:
    image: zabbix/zabbix-agent2:latest
    container_name: mysql-agent
    environment:
      ZBX_HOSTNAME: "Mysql Server"
      ZBX_SERVER_HOST: "zabbix-server"
    depends_on:
      - zabbix-server
    restart: always
    networks:
      - zabbix-net

volumes:
  mysql-data:
  prometheus-data:
  grafana-data:

networks:
  zabbix-net:
    external: true
    name: ia-monitoracao_zabbix-net
